name: COPR Build  

on:  
  schedule:  
    - cron: '0 0 * * *'  # Run daily at midnight  
  workflow_dispatch:  
    inputs:  
      force_rebuild:  
        description: 'Force rebuild even if version has not changed'  
        required: true  
        type: boolean  
        default: false  
  push:  
    paths:  
      - 'mudlet.spec'    # Trigger on spec file changes  

permissions:  
  contents: write


jobs:  
  check-and-build:  
    runs-on: ubuntu-latest  
    container:  
      image: fedora:latest  
      options: --privileged  

    steps:  
      - name: Install required packages  
        run: |  
          dnf install -y copr-cli jq curl git rpmdevtools rpm-build

      - name: Configure git safe directory  
        run: git config --global --add safe.directory '*'  

      - uses: actions/checkout@v2  
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Check latest Mudlet version  
        id: check_version  
        run: |  
          GITHUB_VERSION=$(curl -s https://api.github.com/repos/Mudlet/Mudlet/releases/latest | jq -r .tag_name)  
          # Usuń prefix "Mudlet-" z wersji  
          LATEST_VERSION=${GITHUB_VERSION#Mudlet-}  
          CURRENT_VERSION=$(grep "Version:" mudlet.spec | awk '{print $2}')  
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV  
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV  
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then  
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV  
          else  
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV  
          fi  

      - name: Update spec file if new version is available  
        if: env.UPDATE_NEEDED == 'true'  
        run: |  
          # Configure git  
          git config --global user.email "github-actions@github.com"  
          git config --global user.name "GitHub Actions"  
          
          # Update spec file  
          sed -i "s/Version:.*/Version:        ${LATEST_VERSION}/" mudlet.spec  
          TODAY=$(date +"%a %b %d %Y")  
          sed -i "s/^* .*/* ${TODAY} Package Maintainer <your@email.com> - ${LATEST_VERSION}-1/" mudlet.spec  
          sed -i "s/- Initial package/- Update to ${LATEST_VERSION}/" mudlet.spec

      - name: Download sources  
        run: |  
          spectool -g mudlet.spec  

      - name: Configure COPR token  
        run: |  
          mkdir -p ~/.config  
          echo '${{ secrets.COPR_CONFIG }}' > ~/.config/copr  

      - name: Trigger COPR build  
        if: env.UPDATE_NEEDED == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_rebuild == 'true')  
        id: copr_build  
        run: |  
          BUILD_ID=$(copr-cli build ${{ secrets.COPR_USERNAME }}/${{ secrets.COPR_PROJECT }} mudlet.spec | grep -o 'Build ID: [0-9]*' | cut -d' ' -f3)  
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT  
        continue-on-error: true

      - name: Report build status  
        if: always()  
        run: |  
          if [ "${{ env.UPDATE_NEEDED }}" == "true" ]; then
            echo "Build triggered for version ${{ env.LATEST_VERSION }}"  
          else  
            echo "No update needed. Current version: ${{ env.CURRENT_VERSION }}"  
          fi

