name: COPR Build  

on:  
  schedule:  
    - cron: '0 0 * * *'  # Run daily at midnight  
  workflow_dispatch:      # Allow manual trigger  
  push:  
    paths:  
      - 'mudlet.spec'    # Trigger on spec file changes  

jobs:  
  check-and-build:  
    runs-on: ubuntu-latest  
    container:  
      image: fedora:latest  
      options: --privileged  

    steps:  
      - name: Install required packages  
        run: |  
          dnf install -y copr-cli jq curl git  

      - name: Configure git safe directory  
        run: git config --global --add safe.directory '*'  

      - uses: actions/checkout@v2  
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Check latest Mudlet version  
        id: check_version  
        run: |  
          LATEST_VERSION=$(curl -s https://api.github.com/repos/Mudlet/Mudlet/releases/latest | jq -r .tag_name)  
          CURRENT_VERSION=$(grep "Version:" mudlet.spec | awk '{print $2}')  
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV  
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV  
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then  
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV  
          else  
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV  
          fi  

      - name: Update spec file if new version is available  
        if: env.UPDATE_NEEDED == 'true'  
        run: |  
          # Configure git  
          git config --global user.email "github-actions@github.com"  
          git config --global user.name "GitHub Actions"  
          
          # Update spec file  
          sed -i "s/Version:.*/Version:        ${LATEST_VERSION}/" mudlet.spec  
          TODAY=$(date +"%a %b %d %Y")  
          sed -i "s/^* .*/* ${TODAY} Package Maintainer <your@email.com> - ${LATEST_VERSION}-1/" mudlet.spec  
          sed -i "s/- Initial package/- Update to ${LATEST_VERSION}/" mudlet.spec  
          
          # Commit and push changes  
          git add mudlet.spec  
          git commit -m "Update to version ${LATEST_VERSION}"  
          git push  

      - name: Setup COPR config  
        env:  
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}  
          COPR_USERNAME: ${{ secrets.COPR_USERNAME }}  
        run: |  
          mkdir -p ~/.config  
          echo "[copr-cli]" > ~/.config/copr  
          echo "login = $COPR_TOKEN" >> ~/.config/copr  
          echo "username = $COPR_USERNAME" >> ~/.config/copr  
          echo "copr_url = https://copr.fedorainfracloud.org" >> ~/.config/copr  
          chmod 600 ~/.config/copr  

      - name: Download sources  
        run: |  
          spectool -g mudlet.spec  

      - name: Trigger COPR build  
        if: env.UPDATE_NEEDED == 'true' || github.event_name == 'workflow_dispatch'  
        run: |  
          copr-cli build ${{ secrets.COPR_USERNAME }}/${{ secrets.COPR_PROJECT }} mudlet.spec  

      - name: Report build status  
        if: always()  
        run: |  
          if [ "${{ env.UPDATE_NEEDED }}" == "true" ]; then  
            echo "Build triggered for version ${{ env.LATEST_VERSION }}"  
          else  
            echo "No update needed. Current version: ${{ env.CURRENT_VERSION }}"  
          fi

