name: Build libzip  

on:  
  push:  
    paths:  
      - 'compat-lua-zip.spec'  
  workflow_dispatch:  

jobs:  
  build-and-publish:  
    runs-on: ubuntu-latest  

    container:  
      image: fedora:latest  
      options: --privileged  

    steps:  
      # Install required packages  
      - name: Install required packages  
        run: |  
          dnf install -y git-core copr-cli jq curl rpmdevtools rpm-build  
          git --version  

      # Checkout the repository  
      - name: Checkout code  
        uses: actions/checkout@v4  
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}  
          fetch-depth: 0  

      # Configure git safe directory  
      - name: Configure git safe directory  
        run: git config --global --add safe.directory '*'  

      # Configure Copr CLI  
      - name: Configure Copr CLI  
        run: |  
          mkdir -p ~/.config  
          echo "${{ secrets.COPR_CONFIG }}" > ~/.config/copr  
          chmod 600 ~/.config/copr  

      # Increment the build number in the spec file  
      - name: Increment build number  
        run: |  
          SPEC_FILE="compat-lua-zip.spec"  
          if [ -f "$SPEC_FILE" ]; then  
            RELEASE=$(grep -E '^Release:' "$SPEC_FILE" | awk '{print $2}' | cut -d'%' -f1)  
            NEW_RELEASE=$((RELEASE + 1))  
            sed -i "s/^Release:.*$/Release:        ${NEW_RELEASE}%{?dist}/" "$SPEC_FILE"  
            echo "Updated Release to ${NEW_RELEASE}"  
          else  
            echo "Spec file not found!"  
            exit 1  
          fi  

      # Submit the spec file to Copr  
      - name: Submit to Copr  
        run: |  
          copr-cli build "${{ secrets.COPR_PROJECT }}" compat-lua-zip.spec  

      # Commit and push the updated spec file  
      - name: Commit and push updated spec file  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |  
          git config user.name "GitHub Actions"  
          git config user.email "actions@github.com"  
          git add compat-lua-zip.spec  
          git commit -m "Incremented build number in spec file"  
          git push

